use_frameworks!

platform :ios, '9.0'

target 'MWTableViewCellSeparatorLineSwift_Example' do
  pod 'MWTableViewCellSeparatorLineSwift', :path => '../'

  target 'MWTableViewCellSeparatorLineSwift_Tests' do
    inherit! :search_paths

    
  end
end
